"""Generates the adaptive launcher icon (VectorDrawables) and an SVG/PNG preview from one spec."""
import os, sys
RES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../app/src/main/res")

def rr(x, y, w, h, r):
    return (f"M{x+r},{y} h{w-2*r} a{r},{r} 0 0 1 {r},{r} v{h-2*r} a{r},{r} 0 0 1 {-r},{r} "
            f"h{-(w-2*r)} a{r},{r} 0 0 1 {-r},{-r} v{-(h-2*r)} a{r},{r} 0 0 1 {r},{-r} z")
def circ(cx, cy, r):
    return f"M{cx-r},{cy} a{r},{r} 0 1 0 {2*r},0 a{r},{r} 0 1 0 {-2*r},0 z"

# ---------- geometry (108x108 viewport, keep content in the 66dp safe circle) ----------
BAYS = [(31, "#3DFFA8"), (44, "#22D3EE"), (57, "#22D3EE")]
BX, BW, BH = 34, 40, 11
def bay_with_holes(y):
    body = rr(BX, y, BW, BH, 3)
    slot = rr(38.5, y + 4.25, 17, 2.5, 1.25)
    vents = " ".join(rr(60 + i * 3.2, y + 3.5, 1.4, 5, 0.7) for i in range(1))
    return body + " " + slot
def leds(y):
    return [circ(64.5, y + 5.5, 1.8), circ(69.5, y + 5.5, 1.8)]

NET_STROKE = "M54,68 V76 M54,72 H45 V76 M54,72 H63 V76"
NODES = [circ(45, 78, 2.4), circ(54, 78, 2.4), circ(63, 78, 2.4)]

# background circuit traces (subtle)
TRACES = [
    "M14,42 H22 L26,46 V52", "M14,62 H24 L28,58", "M94,42 H86 L82,46 V52", "M94,62 H84 L80,58",
    "M40,14 V22 L44,26", "M68,14 V22 L64,26",
]
TRACE_NODES = [circ(26, 53.5, 1.5), circ(28.8, 57.2, 1.5), circ(82, 53.5, 1.5), circ(79.2, 57.2, 1.5), circ(44.8, 26.8, 1.5), circ(63.2, 26.8, 1.5)]

BG_GRAD = ("linear", 0, 0, 108, 108, [(0, "#06142E"), (0.55, "#0A3A78"), (1, "#0E8FA8")])
BAY_GRAD = ("linear", 0, 28, 0, 70, [(0, "#FFFFFF"), (1, "#CFE8FF")])
GLOW = ("radial", 54, 50, 44, None, [(0, "#3322D3EE"), (1, "#0022D3EE")])

def layer_bg():
    items = [dict(d="M0,0h108v108h-108z", fill=BG_GRAD), dict(d="M0,0h108v108h-108z", fill=GLOW)]
    items += [dict(d=t, stroke="#5522D3EE", width=1.1) for t in TRACES]
    items += [dict(d=n, fill="#8822D3EE") for n in TRACE_NODES]
    return items

def layer_fg(mono=False):
    white = "#FFFFFFFF"
    items = []
    for y, led in BAYS:
        items.append(dict(d=bay_with_holes(y), fill=white if mono else BAY_GRAD, evenodd=True))
        if not mono:
            for i, l in enumerate(leds(y)):
                items.append(dict(d=l, fill=led if i == 0 else "#0B3B7A"))
    if mono:  # LEDs become holes-free dots; keep silhouette simple
        pass
    items.append(dict(d=NET_STROKE, stroke=white if mono else "#7DF4FF", width=2.2, cap="round"))
    items += [dict(d=n, fill=white if mono else "#7DF4FF") for n in NODES]
    return items

# ---------- writers ----------
def hexa(c):  # SVG color + opacity from #AARRGGBB / #RRGGBB
    c = c.lstrip("#")
    if len(c) == 8: return "#" + c[2:], int(c[:2], 16) / 255
    return "#" + c, 1.0

def vd_color(c):
    c = c.lstrip("#")
    return "#" + (c if len(c) == 8 else "FF" + c)

def vd_grad(g):
    kind, a, b, c, d, stops = g
    s = "".join(f'<item android:offset="{o}" android:color="{vd_color(col)}"/>' for o, col in stops)
    if kind == "linear":
        attrs = f'android:type="linear" android:startX="{a}" android:startY="{b}" android:endX="{c}" android:endY="{d}"'
    else:
        attrs = f'android:type="radial" android:centerX="{a}" android:centerY="{b}" android:gradientRadius="{c}"'
    return f'<aapt:attr name="android:fillColor"><gradient {attrs}>{s}</gradient></aapt:attr>'

def write_vd(name, items):
    out = ['<?xml version="1.0" encoding="utf-8"?>',
           '<!-- Generated by tools/icon/gen.py (see README: app icon). -->',
           '<vector xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt"',
           '    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">']
    for it in items:
        a = [f'android:pathData="{it["d"]}"']
        inner = ""
        if "fill" in it:
            if isinstance(it["fill"], tuple): inner = vd_grad(it["fill"])
            else: a.append(f'android:fillColor="{vd_color(it["fill"])}"')
        if "stroke" in it:
            a += [f'android:strokeColor="{vd_color(it["stroke"])}"', f'android:strokeWidth="{it["width"]}"',
                  f'android:strokeLineCap="{it.get("cap", "round")}"', 'android:strokeLineJoin="round"']
        if it.get("evenodd"): a.append('android:fillType="evenOdd"')
        out.append(f'    <path {" ".join(a)}>{inner}</path>' if inner else f'    <path {" ".join(a)} />')
    out.append('</vector>\n')
    open(os.path.join(RES, "drawable", name), "w").write("\n".join(out))

gid = [0]
def svg_items(items, defs):
    out = []
    for it in items:
        a = [f'd="{it["d"]}"']
        if "fill" in it:
            f = it["fill"]
            if isinstance(f, tuple):
                gid[0] += 1; i = f"g{gid[0]}"
                kind, x1, y1, x2, y2, stops = f
                st = "".join(f'<stop offset="{o}" stop-color="{hexa(c)[0]}" stop-opacity="{hexa(c)[1]:.3f}"/>' for o, c in stops)
                if kind == "linear":
                    defs.append(f'<linearGradient id="{i}" gradientUnits="userSpaceOnUse" x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}">{st}</linearGradient>')
                else:
                    defs.append(f'<radialGradient id="{i}" gradientUnits="userSpaceOnUse" cx="{x1}" cy="{y1}" r="{x2}">{st}</radialGradient>')
                a.append(f'fill="url(#{i})"')
            else:
                c, o = hexa(f); a.append(f'fill="{c}" fill-opacity="{o:.3f}"')
        else:
            a.append('fill="none"')
        if "stroke" in it:
            c, o = hexa(it["stroke"])
            a.append(f'stroke="{c}" stroke-opacity="{o:.3f}" stroke-width="{it["width"]}" stroke-linecap="{it.get("cap","round")}" stroke-linejoin="round"')
        if it.get("evenodd"): a.append('fill-rule="evenodd"')
        out.append(f'<path {" ".join(a)}/>')
    return out

def icon_svg(mask, fg_items, bg_items, size):
    defs, body = [], []
    body += svg_items(bg_items, defs) + svg_items(fg_items, defs)
    clip = {"circle": '<circle cx="54" cy="54" r="54"/>', "squircle": '<rect x="0" y="0" width="108" height="108" rx="30"/>'}[mask]
    # Launchers show the central 72dp of the 108dp layers.
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" viewBox="18 18 72 72">'
            f'<defs>{"".join(defs)}<clipPath id="m"><g transform="translate(18 18) scale(0.6667)">{clip}</g></clipPath></defs>'
            f'<g clip-path="url(#m)">{"".join(body)}</g></svg>')

def mono_svg(size):
    defs = []
    body = svg_items([dict(d="M0,0h108v108h-108z", fill="#1E3A5F")], defs) + svg_items(
        [dict(d=it["d"], **{k: ("#FFBFE3FF" if k in ("fill", "stroke") else v) for k, v in it.items() if k != "d"}) for it in layer_fg(True)], defs)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" viewBox="18 18 72 72">'
            f'<defs><clipPath id="m"><circle cx="54" cy="54" r="36"/></clipPath></defs><g clip-path="url(#m)">{"".join(body)}</g></svg>')

if __name__ == "__main__":
    write_vd("ic_launcher_background.xml", layer_bg())
    write_vd("ic_launcher_foreground.xml", layer_fg())
    write_vd("ic_launcher_monochrome.xml", layer_fg(True))
    import cairosvg, io
    from PIL import Image
    tiles = []
    for mask, size in [("circle", 384), ("squircle", 384), ("circle", 96), ("circle", 48)]:
        tiles.append(Image.open(io.BytesIO(cairosvg.svg2png(bytestring=icon_svg(mask, layer_fg(), layer_bg(), size).encode()))))
    tiles.append(Image.open(io.BytesIO(cairosvg.svg2png(bytestring=mono_svg(96).encode()))))
    W = 384 * 2 + 96 + 60 * 4 + 40
    canvas = Image.new("RGBA", (W, 384 + 80), (245, 247, 250, 255))
    x = 40
    for t in tiles[:2]:
        canvas.alpha_composite(t.convert("RGBA"), (x, 40)); x += 384 + 40
    canvas.alpha_composite(tiles[2].convert("RGBA"), (x, 40))
    canvas.alpha_composite(tiles[3].convert("RGBA"), (x + 24, 160))
    canvas.alpha_composite(tiles[4].convert("RGBA"), (x, 240))
    canvas.save(sys.argv[1] if len(sys.argv) > 1 else "icon-preview.png")
    print("ok")
